name: bark-infinity
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=2.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - huggingface_hub>0.14
  - boto3
  - funcy
  - numpy
  - scipy
  - tokenizers
  - tqdm
  - transformers
  - bandit
  - black
  - codecov
  - flake8
  - hypothesis>=6.14,<7
  - isort>=5.0.0,<6
  - jupyter
  - mypy
  - nbconvert
  - nbformat
  - pydocstyle
  - pylint
  - pytest
  - pytest-cov
  - pysoundfile
  - pathvalidate
  - rich
  - gradio